name: Generate Snake
on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: dist/
